name: .NET format

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x'
        type: string
        required: false
      dotnet-quality:
        description: 'Optional quality of the build. The possible values are: daily, signed, validated, preview, ga.'
        type: string
        required: false

jobs:
  check:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          dotnet-quality: ${{ inputs.dotnet-quality }}
      - name: Add Problem Matcher for dotnet-format
        uses: xt0rted/dotnet-format-problem-matcher@v1.2.0
      - name: Format
        run: dotnet format --verify-no-changes --verbosity detailed
