name: NuGet Lock Files

on:
  workflow_call:
    inputs:
      update-lock-files:
        description: Update lock files if needs. Update job needs secrets.PERSONAL_ACCESS_TOKEN variable.
        type: boolean
        required: false
      dotnet-version:
        description: 'Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x'
        type: string
        required: false
      dotnet-quality:
        description: 'Optional quality of the build. The possible values are: daily, signed, validated, preview, ga.'
        type: string
        required: false
    secrets:
      PERSONAL_ACCESS_TOKEN:
        description: GitHub Personal Access Token to update lock files.
        required: false

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          dotnet-quality: ${{ inputs.dotnet-quality }}

      - name: Restore with lock files
        run: dotnet restore --locked-mode

  update:
    name: Update
    needs: validate
    if: ${{ failure() && inputs.update-lock-files }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          dotnet-quality: ${{ inputs.dotnet-quality }}

      - name: Restore and Update lock files
        run: dotnet restore --force-evaluate
      - name: Run ECLint
        run: |
          npm install -g eclint
          eclint fix "**/packages.lock.json"

      - name: Commit & Push
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "chore(deps): update NuGet lock file"
          git push
